export alias pl = polars
export alias node-info = sinfo -N -o "%10N %8c %10m %15C %20f"
export alias find = find -i
export alias cava = cava -p ~/Yandex.Disk/Backups/linux/config_canva
export alias tree = lstr --icons
export alias nala-fetch = sudo nala fetch --https-only --auto
export alias htop = btm --group_processes -b
export alias colorpicker = termpicker
export alias nvitop = nvitop -m --colorful
export alias "to matlab-matrix" = to csv -ns " "
export alias R = R --quiet --no-save
export alias ncdu = ncdu --color dark
export alias cal = cal --week-start mo
export alias bat = bat --paging never --theme ansi
export alias nu-clean = cargo clean
export alias open-config = zed $nu.config-path
export alias wsp = nchat
export alias png = ping -c 4 -w 4 -q 1.1.1.1
export alias cputemp = tlp-stat -t
export alias takephoto = ffmpeg -y -f video4linux2 -s 1280x720 -i /dev/video0 -ss 0:0:2 -frames 1 ~/photo.jpg
export alias print-list = lpstat -R
export alias apagar = systemctl poweroff -i
export alias reiniciar = systemctl reboot -i
export alias get-mac = open /sys/class/net/wlo1/address
export alias get-wg = xdotool selectwindow getwindowgeometry
export alias btop = btm --battery --hide_avg_cpu --group_processes
export alias mute = amixer -q -D pulse sset Master mute
export alias unmute = amixer -q -D pulse sset Master unmute
export alias max-vol = amixer -D pulse sset Master Playback 65536
export alias "math mean" = math avg
export alias "math std" = math stddev
export alias discord = oxicord
export alias weather = linecast weather --metric

# export alias s = subl
