#!/usr/bin/python3

#Jdownloader wrapper V2.0
#necessary 
#pip3 install myjdapi

def main():   
   import myjdapi, datetime, json
   from sys import exit

   import argparse
   parser = argparse.ArgumentParser()

   parser.add_argument("-b", "--ubb", dest = "ubb", default = "0", help="ubb jdown")

   args = parser.parse_args()

   if args.ubb == "0":
      dev = "kira"
   else :
      dev = "ubb"
   
   #jdownloader instance
   jd=myjdapi.Myjdapi()
   
   jd.connect("kurokirasama@gmail.com","HKxzJdownloader")
   
   jd.update_devices()
   
   try:
      device=jd.get_device("JDownloader@" + dev) 
   except myjdapi.exception.MYJDDeviceNotFoundException:
      print(json.dumps({"message":"device not found"}));
      exit() 
   
   #downloads
   full_query = device.downloads.query_packages([{
                   "bytesLoaded" : True,
                   "bytesTotal" : True,
                   "comment" : False,
                   "enabled" : True,
                   "eta" : True,
                   "priority" : False,
                   "finished" : True,
                   "running" : True,
                   "speed" : True,
                   "status" : True,
                   "childCount" : True,
                   "hosts" : True,
                   "saveTo" : False,
                   "maxResults" : -1,
                   "startAt" : 0,
                   "statusIconKey" : False,
                   "uuid" : True,
               }])
   
   if len(full_query) == 0 :
      print(json.dumps({"message":"No downloads found!"}));
      exit()
   
   #parsing
   downloads = []
   for download in full_query:
      download_info = {
        "uuid": download["uuid"],
        "name": download["name"],
        "hosts": download["hosts"][0] if "hosts" in download and len(download["hosts"]) > 0 else "",
        "childCount": download.get("childCount", ""),
        "eta": download.get("eta", ""),
        "speed": download.get("speed") / (2**20) if "speed" in download else "",
        "bytesLoaded": download.get("bytesLoaded", "") / 1000000,
        "bytesTotal": download.get("bytesTotal", "") / 1000000,
      }
   
   downloads.append(download_info)

   # print the final JSON structure
   print(json.dumps(downloads))

if __name__ == '__main__':
   main()