export alias "pl agg" = polars agg
export alias "pl agg-groups" = polars agg-groups
export alias "pl all-false" = polars all-false
export alias "pl all-true" = polars all-true
export alias "pl append" = polars append
export alias "pl arg-max" = polars arg-max
export alias "pl arg-min" = polars arg-min
export alias "pl arg-sort" = polars arg-sort
export alias "pl arg-true" = polars arg-true
export alias "pl arg-unique" = polars arg-unique
export alias "pl arg-where" = polars arg-where
export alias "pl as" = polars as
export alias "pl as-date" = polars as-date
export alias "pl as-datetime" = polars as-datetime
export alias "pl cache" = polars cache
export alias "pl cast" = polars cast
export alias "pl col" = polars col
export alias "pl collect" = polars collect
export alias "pl columns" = polars columns
export alias "pl concat" = polars concat
export alias "pl concat-str" = polars concat-str
export alias "pl contains" = polars contains
export alias "pl convert-time-zone" = polars convert-time-zone
export alias "pl count" = polars count
export alias "pl count-null" = polars count-null
export alias "pl cumulative" = polars cumulative
export alias "pl cut" = polars cut
export alias "pl datepart" = polars datepart
export alias "pl decimal" = polars decimal
export alias "pl drop" = polars drop
export alias "pl drop-duplicates" = polars drop-duplicates
export alias "pl drop-nulls" = polars drop-nulls
export alias "pl dummies" = polars dummies
export alias "pl entropy" = polars entropy
export alias "pl explode" = polars explode
export alias "pl expr-not" = polars expr-not
export alias "pl fill-nan" = polars fill-nan
export alias "pl fill-null" = polars fill-null
export alias "pl filter" = polars filter
export alias "pl filter-with" = polars filter-with
export alias "pl first" = polars first
export alias "pl flatten" = polars flatten
export alias "pl get" = polars get
export alias "pl get-day" = polars get-day
export alias "pl get-hour" = polars get-hour
export alias "pl get-minute" = polars get-minute
export alias "pl get-month" = polars get-month
export alias "pl get-nanosecond" = polars get-nanosecond
export alias "pl get-ordinal" = polars get-ordinal
export alias "pl get-second" = polars get-second
export alias "pl get-week" = polars get-week
export alias "pl get-weekday" = polars get-weekday
export alias "pl get-year" = polars get-year
export alias "pl group-by" = polars group-by
export alias "pl horizontal" = polars horizontal
export alias "pl implode" = polars implode
export alias "pl integer" = polars integer
export alias "pl into-df" = polars into-df
export alias "pl into-dtype" = polars into-dtype
export alias "pl into-lazy" = polars into-lazy
export alias "pl into-nu" = polars into-nu
export alias "pl into-repr" = polars into-repr
export alias "pl into-schema" = polars into-schema
export alias "pl is-duplicated" = polars is-duplicated
export alias "pl is-in" = polars is-in
export alias "pl is-not-null" = polars is-not-null
export alias "pl is-null" = polars is-null
export alias "pl is-unique" = polars is-unique
export alias "pl join" = polars join
export alias "pl join-where" = polars join-where
export alias "pl last" = polars last
export alias "pl len" = polars len
export alias "pl list-contains" = polars list-contains
export alias "pl lit" = polars lit
export alias "pl lowercase" = polars lowercase
export alias "pl map-batches" = polars map-batches
export alias "pl math" = polars math
export alias "pl math abs" = polars math abs
export alias "pl math bitwise-and" = polars math bitwise-and
export alias "pl math bitwise-count-ones" = polars math bitwise-count-ones
export alias "pl math bitwise-count-zeros" = polars math bitwise-count-zeros
export alias "pl math bitwise-leading-ones" = polars math bitwise-leading-ones
export alias "pl math bitwise-leading-zeros" = polars math bitwise-leading-zeros
export alias "pl math bitwise-or" = polars math bitwise-or
export alias "pl math bitwise-trailing-ones" = polars math bitwise-trailing-ones
export alias "pl math bitwise-trailing-zeros" = polars math bitwise-trailing-zeros
export alias "pl math bitwise-xor" = polars math bitwise-xor
export alias "pl math cos" = polars math cos
export alias "pl math dot" = polars math dot
export alias "pl math exp" = polars math exp
export alias "pl math log" = polars math log
export alias "pl math log1p" = polars math log1p
export alias "pl math sign" = polars math sign
export alias "pl math sin" = polars math sin
export alias "pl math sqrt" = polars math sqrt
export alias "pl max" = polars max
export alias "pl mean" = polars mean
export alias "pl median" = polars median
export alias "pl min" = polars min
export alias "pl n-unique" = polars n-unique
export alias "pl not" = polars not
export alias "pl open" = polars open
export alias "pl otherwise" = polars otherwise
export alias "pl over" = polars over
export alias "pl pivot" = polars pivot
export alias "pl profile" = polars profile
export alias "pl qcut" = polars qcut
export alias "pl quantile" = polars quantile
export alias "pl query" = polars query
export alias "pl rename" = polars rename
export alias "pl replace" = polars replace
export alias "pl replace-time-zone" = polars replace-time-zone
export alias "pl reverse" = polars reverse
export alias "pl rolling" = polars rolling
export alias "pl sample" = polars sample
export alias "pl save" = polars save
export alias "pl schema" = polars schema
export alias "pl select" = polars select
export alias "pl selector" = polars selector
export alias "pl selector all" = polars selector all
export alias "pl selector alpha" = polars selector alpha
export alias "pl selector alphanumeric" = polars selector alphanumeric
export alias "pl selector array" = polars selector array
export alias "pl selector binary" = polars selector binary
export alias "pl selector boolean" = polars selector boolean
export alias "pl selector by-dtype" = polars selector by-dtype
export alias "pl selector by-index" = polars selector by-index
export alias "pl selector by-name" = polars selector by-name
export alias "pl selector categorical" = polars selector categorical
export alias "pl selector contains" = polars selector contains
export alias "pl selector date" = polars selector date
export alias "pl selector datetime" = polars selector datetime
export alias "pl selector decimal" = polars selector decimal
export alias "pl selector digit" = polars selector digit
export alias "pl selector duration" = polars selector duration
export alias "pl selector empty" = polars selector empty
export alias "pl selector ends-with" = polars selector ends-with
export alias "pl selector enum" = polars selector enum
export alias "pl selector exclude" = polars selector exclude
export alias "pl selector first" = polars selector first
export alias "pl selector float" = polars selector float
export alias "pl selector integer" = polars selector integer
export alias "pl selector last" = polars selector last
export alias "pl selector list" = polars selector list
export alias "pl selector matches" = polars selector matches
export alias "pl selector nested" = polars selector nested
export alias "pl selector not" = polars selector not
export alias "pl selector numeric" = polars selector numeric
export alias "pl selector object" = polars selector object
export alias "pl selector signed-integer" = polars selector signed-integer
export alias "pl selector starts-with" = polars selector starts-with
export alias "pl selector string" = polars selector string
export alias "pl selector struct" = polars selector struct
export alias "pl selector temporal" = polars selector temporal
export alias "pl selector unsigned-integer" = polars selector unsigned-integer
export alias "pl set" = polars set
export alias "pl set-with-idx" = polars set-with-idx
export alias "pl shape" = polars shape
export alias "pl shift" = polars shift
export alias "pl slice" = polars slice
export alias "pl sort-by" = polars sort-by
export alias "pl std" = polars std
export alias "pl store-get" = polars store-get
export alias "pl store-ls" = polars store-ls
export alias "pl store-rm" = polars store-rm
export alias "pl str-join" = polars str-join
export alias "pl str-lengths" = polars str-lengths
export alias "pl str-replace" = polars str-replace
export alias "pl str-replace-all" = polars str-replace-all
export alias "pl str-slice" = polars str-slice
export alias "pl str-split" = polars str-split
export alias "pl str-strip-chars" = polars str-strip-chars
export alias "pl strftime" = polars strftime
export alias "pl struct-json-encode" = polars struct-json-encode
export alias "pl sum" = polars sum
export alias "pl summary" = polars summary
export alias "pl take" = polars take
export alias "pl truncate" = polars truncate
export alias "pl unique" = polars unique
export alias "pl unnest" = polars unnest
export alias "pl unpivot" = polars unpivot
export alias "pl uppercase" = polars uppercase
export alias "pl value-counts" = polars value-counts
export alias "pl var" = polars var
export alias "pl when" = polars when
export alias "pl with-column" = polars with-column
